[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.0"
tag_format = "$version"
version_files =  [
    "package.json:version"
]
version_scheme = "semver"
changelog_merge_prerelease = true