name: Bump version

on:
    push:
        branches:
            - master

jobs:
    tests:
        if: "!startsWith(github.event.head_commit.message, 'bump:')"
        runs-on: ubuntu-latest
        env:
            DATA_URL: https://example.com
        steps:
            - name: Check out
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Install dependencies
              run: npm install
            - name: Run unit tests
              run: npm test
            - name: Summary
              if: always()
              uses: test-summary/action@v2
              with:
                paths: |
                  reports/test-results.xml

    bump-version:
        needs: tests
        if: ${{ success() }}
        runs-on: ubuntu-latest
        name: 'Bump version and create changelog with commitizen'
        steps:
            - name: Check out
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

            - name: Create bump and changelog
              uses: commitizen-tools/commitizen-action@master
              with:
                  github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
